# =============================================================
# build-preamble.ps1
#
# Concatenates include/**/*.tex into preamble.sty at vault root.
#
# Input order is derived from main.tex \input{...} lines,
# so editing main.tex automatically updates the build order.
#
# Usage (from vault root):
#   pwsh -ExecutionPolicy Bypass -File tex/obsidian/build-preamble.ps1
# =============================================================

$ErrorActionPreference = "Stop"
$texDir     = Split-Path $PSScriptRoot -Parent          # tex/
$vaultRoot  = Split-Path $texDir -Parent                # vault root
$includeDir = Join-Path $texDir "include"
$mainTex    = Join-Path $texDir "main.tex"
$outFile    = Join-Path $vaultRoot "preamble.sty"

if (-not (Test-Path $mainTex)) {
    Write-Error "Cannot find $mainTex"
    exit 1
}

# --- 1. Parse \input order from main.tex -------------------------------------
$pattern = '\\input\{include/tex_symbols/include/([^}]+)\}'
$relPaths = @(
    Select-String -Path $mainTex -Pattern $pattern -AllMatches |
        ForEach-Object { $_.Matches } |
        ForEach-Object { $_.Groups[1].Value }
)

if ($relPaths.Count -eq 0) {
    Write-Error "No \input{include/tex_symbols/include/...} lines found in $mainTex"
    exit 1
}

# --- 2. Header ---------------------------------------------------------------
$now = Get-Date
$header = @"
% =============================================================
% Auto-generated by build-preamble.ps1 -- DO NOT EDIT
% Edit sources in tex/include/ instead, then re-run the build.
%
% Built : $($now.ToString("yyyy-MM-dd HH:mm:ss"))
% Source: gunheeShin/tex_symbols (vault submodule at tex/)
% Order : derived from tex/main.tex (\input order)
% =============================================================
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{preamble}[$($now.ToString("yyyy/MM/dd")) personal math macros]


"@

# --- 3. Concatenate ----------------------------------------------------------
$bodyParts = New-Object System.Collections.Generic.List[string]
$missing   = New-Object System.Collections.Generic.List[string]

foreach ($rel in $relPaths) {
    $file = Join-Path $includeDir $rel
    if (Test-Path $file) {
        $bodyParts.Add("")
        $bodyParts.Add("% ----- include/$rel -----")
        $bodyParts.Add((Get-Content $file -Raw).TrimEnd())
    } else {
        $missing.Add($rel)
        Write-Warning "Missing: include/$rel"
    }
}

# --- 4. Write UTF-8 without BOM ----------------------------------------------
$footer    = "`n`n\endinput`n"
$content   = $header + ($bodyParts -join "`n") + $footer
$utf8NoBom = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($outFile, $content, $utf8NoBom)

$built = $relPaths.Count - $missing.Count
Write-Host "Built preamble.sty: $built/$($relPaths.Count) files -> $outFile" -ForegroundColor Green
if ($missing.Count -gt 0) {
    Write-Host "  Missing: $($missing -join ', ')" -ForegroundColor Yellow
}
