#!/usr/bin/env bash
# =============================================================
# build-preamble.sh
#
# Bash port of build-preamble.ps1 for Linux/macOS.
# Concatenates include/**/*.tex into preamble.sty at vault root.
#
# Input order is derived from main.tex \input{...} lines.
#
# Usage (from anywhere):
#   bash tex/obsidian/build-preamble.sh
# =============================================================
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
tex_dir="$(dirname "$script_dir")"           # tex/
vault_root="$(dirname "$tex_dir")"           # vault root
include_dir="$tex_dir/include"
main_tex="$tex_dir/main.tex"
out_file="$vault_root/preamble.sty"

[[ -f "$main_tex" ]] || { echo "Cannot find $main_tex" >&2; exit 1; }

# --- 1. Parse \input order from main.tex ------------------------------------
mapfile -t rel_paths < <(
  grep -oE '\\input\{include/tex_symbols/include/[^}]+\}' "$main_tex" \
    | sed -E 's|\\input\{include/tex_symbols/include/([^}]+)\}|\1|'
)

if [[ ${#rel_paths[@]} -eq 0 ]]; then
  echo "No \\input{include/tex_symbols/include/...} lines found in $main_tex" >&2
  exit 1
fi

# --- 2. Header --------------------------------------------------------------
now_full="$(date '+%Y-%m-%d %H:%M:%S')"
now_date="$(date '+%Y/%m/%d')"

# --- 3. Concatenate ---------------------------------------------------------
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  cat <<EOF
% =============================================================
% Auto-generated by build-preamble.sh -- DO NOT EDIT
% Edit sources in tex/include/ instead, then re-run the build.
%
% Built : $now_full
% Source: gunheeShin/tex_symbols (vault submodule at tex/)
% Order : derived from tex/main.tex (\input order)
% =============================================================
\NeedsTeXFormat{LaTeX2e}
\ProvidesPackage{preamble}[$now_date personal math macros]

EOF

  built=0
  missing=()
  for rel in "${rel_paths[@]}"; do
    file="$include_dir/$rel"
    if [[ -f "$file" ]]; then
      printf '\n%% ----- include/%s -----\n' "$rel"
      # strip trailing whitespace/newlines
      sed -e :a -e '/^[[:space:]]*$/{$d;N;ba' -e '}' "$file"
      built=$((built + 1))
    else
      missing+=("$rel")
      echo "Missing: include/$rel" >&2
    fi
  done

  printf '\n\n\\endinput\n'
} > "$tmp"

mv "$tmp" "$out_file"
trap - EXIT

echo "Built preamble.sty: $built/${#rel_paths[@]} files -> $out_file"
if [[ ${#missing[@]} -gt 0 ]]; then
  echo "  Missing: ${missing[*]}"
fi

# --- 4. Generate macros.json + .vscode/settings.json ------------------------
python3 "$script_dir/sty-to-json.py" \
  "$out_file" \
  "$vault_root/macros.json" \
  "$vault_root/.vscode/settings.json"
